version: "3.7"

services:
  runner:
    image: myoung34/github-runner:latest
    restart: always
    volumes:
      #linux
      #- /var/run/docker.sock:/var/run/docker.sock
      #windows
      - //var/run/docker.sock:/var/run/docker.sock
      #- /usr/local/bin/docker:/usr/bin/docker

    env_file:
      - .env
    environment:
      RUNNER_SCOPE: repo
      RUNNER_NAME_PREFIX: locpc-runner
      LABELS: some-label
      REPO_URL: https://github.com/cec-tris/umap
      EPHEMERAL: 1
      #ACCESS_TOKEN: __GITHUB_ACCESS_TOKEN__ # setting in .env file


    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1G
        # reservations:
        #   cpus: '0.2'
        #   memory: 256M