name: Test GitHub Actions
# on: [push]
on:
  push:
    branches: [cicd/*]

env:
  DAY_OF_WEEK: Monday
  env_var1: ${{ vars.UMAP_DOMAIN }}
  env_var2: ${{ secrets.DOCKER_REGISTRY }}
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, some-label] #ubuntu-18.04
    # defaults:
    #   run:
    #     working-directory: umap-web
    environment: UMAP_DEV
    steps:
      - run: echo "day of week $DAY_OF_WEEK" # thay the khi su dung
      - run: echo "day of week ${{ env.DAY_OF_WEEK }}" # duoc thay the truoc khi chay
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo " Environment UMAP_DOMAIN ${{ env.env_var1 }} - ${{ vars.UMAP_DOMAIN }}"
      - run: echo " Environment DOCKER_REGISTRY ${{ env.env_var2 }} - ${{ secrets.DOCKER_REGISTRY }}"

      - name: Check out repository code
        uses: actions/checkout@v3

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: List files in umap-web
        working-directory: umap-web
        run: |
            ls .

      - name: List files after using working-directory
        run: |
            ls .

      - name: Setup node  ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'umap-web/package-lock.json'
    
      - name: npm ci
        working-directory: umap-web
        run: npm ci

      - name: npm run build
        working-directory: umap-web
        run: npm run build 

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./umap-web
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/umap/web4umap:test

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}

      # - name: SSH deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.UMAP_SSH_HOST }}
      #     username: ${{ secrets.UMAP_SSH_USER }}
      #     key: ${{ secrets.UMAP_SSH_PRIVATE_KEY }}
      #     script: |
      #      ./deploy.sh

      - run: echo "🍏 This job's status is ${{ job.status }}."